#!/bin/sh

fish_add_path -g $HOME/.scripts/

#autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pkill picom
picom --experimental-backends &
feh --bg-fill ~/.wallpapers/4.jpg
~/.config/polybar/launch.sh 

#monitor
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d 1 2 3 4 5 6

#window information
bspc config border_width 0 
bspc config window_gap 9
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

#rules
bspc rule -a mumble state=floating follow=on focus=on